version: "3"

services:
  www:
    build: ./noisitor-www
    ports:
      - ${WEB_PORT}:8080

  frontend:
    build: ./noisitor-frontend

  backend:
    build: ./noisitor-backend
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./dbmanager/db.py:/app/db.py

  monitor:
    build: ./noisitord
    environment:
      - NOISITOR_IFACE=${NOISITOR_IFACE}
      - NOISITOR_PORTS=${NOISITOR_PORTS}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - NOISITORD_DEBUG=${NOISITORD_DEBUG}
    volumes:
      - ./ip2location:/ip2location
      - ./dbmanager/db.py:/app/db.py
    network_mode: "host"
    cap_add:
      - NET_ADMIN

  db:
    image: mongo
    restart: always
    volumes:
      - ./db:/data/db
    ports:
      - ${DB_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}

  postgres-db:
    image: postgres:16
    restart: always
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=noisitor
      - POSTGRES_PASSWORD=${DB_PASSWORD}
