version: "3"

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./old-db:/data/db
    
  postgres:
    image: postgres
    restart: always
    volumes:
      - ../db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  migrator:
    build: .
    volumes:
      - ../ip2location:/ip2location
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
